[profile.default]
src = "vendor/midnight/src"
test = "test"
libs = ["vendor/midnight/lib"]
via_ir = true
optimizer = true
optimizer_runs = 466
bytecode_hash = "none"
evm_version = "osaka"
solc_version = "0.8.34"
fs_permissions = [
    { access = "read", path = "./test" },
    { access = "read-write", path = "./out" },
]

[profile.default.fuzz]
runs = 1
